language: ruby

services:
  - docker
jdk:
  - openjdk11
branches:
  only:
    - main

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew jibDockerBuild"


# 배포에 필요한 파일들만 archive 에 옮겨서 archive/archive.zip 파일로 만든다.
#before_deploy:
#  - mkdir -p archive
#  - cp build/libs/*.jar archive/application.jar
#  - cp -r ./.ebextensions archive/.ebextensions
#  - cd archive
#  - ls -al
#  - zip -r archive.zip application.jar .ebextensions
#
deploy:
  provider: script
  script: bash docker-push.sh
  on:
    branch: main
#  provider: elasticbeanstalk
#  zip_file: archive.zip # before_deploy에서 이미 archive로 이동한 상태(cd archive)라 현재 위치에서 archive.zip 전송
#  skip_cleanup: true
#  access_key_id: $AWS_ACCESS_KEY
#  secret_access_key:
#    secure: $AWS_SECRET_KEY
#  region: "ap-northeast-2"
#  app: "sehwa-beanstalk"
#  env: "Sehwabeanstalk-env"
#  bucket_name: "elasticbeanstalk-ap-northeast-2-782016145255"  # S3 bucket name
#  bucket_path: "Server"
#  on:
#    branch: main
#
#after_deploy:
#  - echo "Elastic Beanstalk 배포 진행중입니다."