language: generic

services:
  - docker
jdk:
  - openjdk11
branches:
  only:
    - main

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew jibDockerBuild"

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
  - docker push jrhong95/ahttyduri
  - echo "Pushed to DockerHub!"

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "ahttys-server"
  env: "Ahttysserver-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-782016145255"  # S3 bucket name
  bucket_path: "Server"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

after_deploy:
  - echo "deploy success"

notifications:
  slack: 2021tourapi:2grzt30lYvQYm1FWMtgMAoxu