# @format

version: '3'
services:
  ahttyduri-server:
    image: 'jrhong95/ahttyduri'
    container_name: 'ahttyduri-server'
    environment:
      SPRING_PROFILES_ACTIVE: '${SPRING_PROFILES_ACTIVE}'
      DB_PATH: '${DB_PATH}'
      DB_USER: '${DB_USER}'
      DB_PASSWORD: '${DB_PASSWORD}'
      MONGO_HOST: '${MONGO_HOST}'
      MONGO_PORT: '${MONGO_PORT}'
      MONGO_DB: '${MONGO_DB}'
      MONGO_USER: '${MONGO_USER}'
      MONGO_PASSWORD: '${MONGO_PASSWORD}'
      KAKAO_CLIENT_ID: '${KAKAO_CLIENT_ID}'
      KAKAO_REDIRECT_URI: '${KAKAO_REDIRECT_URI}'
      JWT_KEY: '${JWT_KEY}'
    ports:
      - '8080:8080'

  ahttyduri-proxy:
    restart: always
    build: ./nginx
    container_name: 'ahttyduri-proxy'
    depends_on:
      - ahttyduri-server
    ports:
      - '80:80'

  tmp_contatiner:
    image: 'ubuntu'
    container_name: 'test-container'
    network_mode: 'host'
