version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./db-data/:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "AhttyDuri"
      MYSQL_ROOT_PASSWORD: "ahtty"
      TZ: "Asia/Seoul"

