version: "3"
services:
  ahttyduri-server:
    image: "jrhong95/ahttyduri"
    container_name: "ahttyduri-server"
    environment:
      SPRING_PROFILES_ACTIVE: "${SPRING_PROFILES_ACTIVE}"
      DB_PATH: "${DB_PATH}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "8080:8080"

  ahttyduri-proxy:
    restart: always
    build: ./nginx
    container_name: "ahttyduri-proxy"
    depends_on:
      - ahttyduri-server
    ports:
      - "80:80"
