version: "3"
services:
  backend:
    image: "jrhong95/ahttyduri"
    container_name: "ahttyduri-server"
    environment:
      SPRING_PROFILES_ACTIVE: "${SPRING_PROFILES_ACTIVE}"
      DB_PATH: "${DB_PATH}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "8080:8080"