spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./db-data/testdb;MODE=MySQL
    username: sa
    password: ahtty

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        format-sql: true
        show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

jwt:
  header: Authorization
  secret: YWh0dHlhaHR0eWFodHR5YWh0dHlhaHR0eWFodHR5YWh0dHlhaHR0eQo=
  token-validity-in-minutes: 120

logging:
  level:
    org.springframework.web: debug
    sql: error
    jdbc: off
    jdbc.sqlonly: debug

