spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./db-data/testdb;MODE=MySQL
    username: sa
    password: ahtty
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
  h2:
    console:
      enabled: true
      path: /h2-console


logging:
  level:
    org.springframework.web: debug
    sql: error
    jdbc: off
    jdbc.sqlonly: debug

